# Generated by Django 5.2.17 on 2026-08-21 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(db_index=True, max_length=255)),
                ('body', models.TextField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('answers_count', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('accepted_answers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_questions', to='answers.answersmodel')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
