# Generated by Django 5.2.17 on 2026-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
