# Generated by Django 5.2.17 on 2026-09-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0002_alter_questionmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='accepted_answers',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='accepted_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_questions', to='answers.answersmodel'),
        ),
    ]
